version: "3.8"
services:
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: emails
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: emails
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33067:3306

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
      - 1025:1025
